// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVArzsbfHibx2_dZ0aQ2IzbtzQGmFvkw',
    appId: '1:174371170971:web:822074f09876e18c57343e',
    messagingSenderId: '174371170971',
    projectId: 'pos-system202503',
    authDomain: 'pos-system202503.firebaseapp.com',
    storageBucket: 'pos-system202503.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfvuj8UqlOiD5ypC85yBBdX-h5cMjwZM',
    appId: '1:174371170971:android:13b78638d2d567bb57343e',
    messagingSenderId: '174371170971',
    projectId: 'pos-system202503',
    storageBucket: 'pos-system202503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFm9Xqrx19zknYtWWMVNiOjxbKi3T5tQ',
    appId: '1:174371170971:ios:93c743d03870103857343e',
    messagingSenderId: '174371170971',
    projectId: 'pos-system202503',
    storageBucket: 'pos-system202503.firebasestorage.app',
    iosBundleId: 'com.evanlu.possystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWFm9Xqrx19zknYtWWMVNiOjxbKi3T5tQ',
    appId: '1:174371170971:ios:a303f0ca644448ac57343e',
    messagingSenderId: '174371170971',
    projectId: 'pos-system202503',
    storageBucket: 'pos-system202503.firebasestorage.app',
    iosBundleId: 'com.example.posmacos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbVArzsbfHibx2_dZ0aQ2IzbtzQGmFvkw',
    appId: '1:174371170971:web:38aa11ac7f609e5757343e',
    messagingSenderId: '174371170971',
    projectId: 'pos-system202503',
    authDomain: 'pos-system202503.firebaseapp.com',
    storageBucket: 'pos-system202503.firebasestorage.app',
  );
}
